### ISSUE TITLE
Using submodule

### ISSUE THREAD

**Issue by hadisfr** [kevinxucs/Sublime-Gitignore#5]
Couldn't you use git submodule for _boilerplates_, so it becomes easier to update it?

And isn't there any method to automatically update it? Perhaps a simple script can check _boilerplates_ repo periodically. 🤔

**Comment by kevinxucs** [comment]
Good suggestion, feel free to send an PR

**Comment by hadisfr** [comment]
I made https://github.com/kevinxucs/Sublime-Gitignore/pull/7 in a regular way based on my master branch. Could you merge it, so I try to use submodule in a new PR including only "migrate to submodule" commits?

**Comment by hadisfr** [comment]
As mentioned in https://github.com/kevinxucs/Sublime-Gitignore/pull/8#discussion_r209933521, it's impossible to use _submodule_. Perhaps _subtree_ as in #8.
